;;; aluminium-theme.el --- An elegant theme

(unless (>= emacs-major-version 24)
  (error "Aluminium theme requires Emacs 24 or later!"))

(deftheme aluminium "An arctic, north-bluish clean and elegant theme")

(defgroup aluminium nil
  "Nord theme customizations.
  The theme has to be reloaded after changing anything in this group."
  :group 'faces)

(defcustom aluminium-comment-brightness 0
  "Allows to define a custom comment color brightness with percentage adjustments from 0% - 20%.
  The value must be greater or equal to 0 and less or equal to 20, otherwise the default 'aluminium3' color is used."
  :type 'integer
  :group 'aluminium)

(defcustom aluminium-region-highlight nil
  "Allows to set a region highlight style based on the Aluminium components.
  Valid styles are
    - 'snowstorm' - Uses 'aluminium0' as foreground- and 'aluminium4' as background color
    - 'frost' - Uses 'aluminium0' as foreground- and 'aluminium8' as background color"
  :type 'string
  :group 'aluminium)

(defcustom aluminium-uniform-mode-lines nil
  "Enables uniform activate- and inactive mode lines using 'aluminium3' as background."
  :type 'boolean
  :group 'aluminium)

(setq aluminium-brightened-comments '("#B3A995" "#4e586d" "#505b70" "#525d73" "#556076" "#576279" "#59647c" "#5b677f" "#5d6982" "#5f6c85" "#616e88" "#63718b" "#66738e" "#687591" "#6a7894" "#6d7a96" "#6f7d98" "#72809a" "#75829c" "#78859e" "#7b88a1"))

(defun brightened-comment-color (percent)
  "Returns the brightened comment color for the given percent.
  The value must be greater or equal to 0 and less or equal to 20, otherwise the default 'aluminium3' color is used."
  (if (and (integerp percent)
          (>= percent 0)
          (<= percent 20))
    (nth percent aluminium-brightened-comments)
    (nth 0 aluminium-brightened-comments)))

;;;; Color Constants
(let ((class '((class color) (min-colors 89)))
      (aluminium0 (if (display-graphic-p) "#fdfdfd" nil))
      (aluminium1 (if (display-graphic-p) "#eeeeee" "black"))
      (aluminium2 (if (display-graphic-p) "#e5e5e5" "#e5e5e5"))
      (aluminium3 (if (display-graphic-p) "#d5d5d5" "brightblack"))
      (aluminium4 (if (display-graphic-p) "#272116" "#272116"))
      (aluminium5 (if (display-graphic-p) "#1a160f" "white"))
      (aluminium6 (if (display-graphic-p) "#13100b" "brightwhite"))
      (aluminium7 (if (display-graphic-p) "#704344" "cyan"))
      (aluminium8 (if (display-graphic-p) "#773f2f" "brightcyan"))
      (aluminium9 (if (display-graphic-p) "#7e5e3e" "blue"))
      (aluminium10 (if (display-graphic-p) "#a17e53" "brightblue"))
      (aluminium11 (if (display-graphic-p) "#409e95" "red"))
      (aluminium12 (if (display-graphic-p) "#2f788f" "brightyellow"))
      (aluminium13 (if (display-graphic-p) "#143474" "yellow"))
      (aluminium14 (if (display-graphic-p) "#5c4173" "green"))
      (aluminium15 (if (display-graphic-p) "#4b7152" "magenta"))
      (aluminium-annotation (if (display-graphic-p) "#2f788f" "brightyellow"))
      (aluminium-attribute (if (display-graphic-p) "#704344" "cyan"))
      (aluminium-class (if (display-graphic-p) "#704344" "cyan"))
      (aluminium-comment (if (display-graphic-p) (brightened-comment-color aluminium-comment-brightness) "brightblack"))
      (aluminium-escape (if (display-graphic-p) "#2f788f" "brightyellow"))
      (aluminium-method (if (display-graphic-p) "#773f2f" "brightcyan"))
      (aluminium-keyword (if (display-graphic-p) "#7e5e3e" "blue"))
      (aluminium-numeric (if (display-graphic-p) "#4b7152" "magenta"))
      (aluminium-operator (if (display-graphic-p) "#7e5e3e" "blue"))
      (aluminium-preprocessor (if (display-graphic-p) "#a17e53" "brightblue"))
      (aluminium-punctuation (if (display-graphic-p) "#272116" "#272116"))
      (aluminium-regexp (if (display-graphic-p) "#143474" "yellow"))
      (aluminium-string (if (display-graphic-p) "#5c4173" "green"))
      (aluminium-tag (if (display-graphic-p) "#7e5e3e" "blue"))
      (aluminium-variable (if (display-graphic-p) "#272116" "#D8DEE9"))
      (aluminium-region-highlight-foreground (if (or
    (string= aluminium-region-highlight "frost")
    (string= aluminium-region-highlight "snowstorm")) "#d1cbbf" nil))
  (aluminium-region-highlight-background (if
                                            (string= aluminium-region-highlight "frost") "#773f2f"
                                          (if (string= aluminium-region-highlight "snowstorm") "#272116" "#bcb3a1")))
  (aluminium-uniform-mode-lines-background (if aluminium-uniform-mode-lines "#b3a995" "#fdfdfd")))

;;;; +------------+
;;;; + Core Faces +
;;;; +------------+
  (custom-theme-set-faces
    'aluminium
    ;; +--- Base ---+
    `(bold ((,class (:weight bold))))
    `(bold-italic ((,class (:weight bold :slant italic))))
    `(default ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(error ((,class (:foreground ,aluminium8 :weight bold))))
    `(escape-glyph ((,class (:foreground ,aluminium12))))
    `(font-lock-builtin-face ((,class (:foreground ,aluminium9))))
    `(font-lock-comment-face ((,class (:foreground ,aluminium-comment))))
    `(font-lock-comment-delimiter-face ((,class (:foreground ,aluminium-comment))))
    `(font-lock-constant-face ((,class (:foreground ,aluminium9))))
    `(font-lock-doc-face ((,class (:foreground ,aluminium-comment))))
    `(font-lock-function-name-face ((,class (:foreground ,aluminium8))))
    `(font-lock-keyword-face ((,class (:foreground ,aluminium9))))
    `(font-lock-negation-char-face ((,class (:foreground ,aluminium9))))
    `(font-lock-preprocessor-face ((,class (:foreground ,aluminium10 :weight bold))))
    `(font-lock-reference-face ((,class (:foreground ,aluminium9))))
    `(font-lock-regexp-grouping-backslash ((,class (:foreground ,aluminium13))))
    `(font-lock-regexp-grouping-construct ((,class (:foreground ,aluminium13))))
    `(font-lock-string-face ((,class (:foreground ,aluminium14))))
    `(font-lock-type-face ((,class (:foreground ,aluminium7))))
    `(font-lock-variable-name-face ((,class (:foreground ,aluminium4))))
    `(font-lock-warning-face ((,class (:foreground ,aluminium13))))
    `(italic ((,class (:slant italic))))
    `(shadow ((,class (:foreground ,aluminium3))))
    `(underline ((,class (:underline t))))
    `(warning ((,class (:foreground ,aluminium10 :weight bold))))

    ;; +--- Syntax ---+
    ;; > C
    `(c-annotation-face ((,class (:foreground ,aluminium-annotation))))

    ;; > diff
    `(diff-added ((,class (:foreground ,aluminium14))))
    `(diff-changed ((,class (:foreground ,aluminium13))))
    `(diff-context ((,class (:inherit default))))
    `(diff-file-header ((,class (:foreground ,aluminium8))))
    `(diff-function ((,class (:foreground ,aluminium7))))
    `(diff-header ((,class (:foreground ,aluminium9 :weight bold))))
    `(diff-hunk-header ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(diff-indicator-added ((,class (:foreground ,aluminium14))))
    `(diff-indicator-changed ((,class (:foreground ,aluminium13))))
    `(diff-indicator-removed ((,class (:foreground ,aluminium11))))
    `(diff-nonexistent ((,class (:foreground ,aluminium11))))
    `(diff-refine-added ((,class (:foreground ,aluminium14))))
    `(diff-refine-changed ((,class (:foreground ,aluminium13))))
    `(diff-refine-removed ((,class (:foreground ,aluminium11))))
    `(diff-removed ((,class (:foreground ,aluminium11))))

    ;; +--- UI ---+
    `(border ((,class (:foreground ,aluminium4))))
    `(buffer-menu-buffer ((,class (:foreground ,aluminium4 :weight bold))))
    `(button ((,class (:background ,aluminium0 :foreground ,aluminium8 :box (:line-width 2 :color ,aluminium4 :style sunken-button)))))
    `(completions-annotations ((,class (:foreground ,aluminium9))))
    `(completions-common-part ((,class (:foreground ,aluminium8 :weight bold))))
    `(completions-first-difference ((,class (:foreground ,aluminium11))))
    `(custom-button ((,class (:background ,aluminium0 :foreground ,aluminium8 :box (:line-width 2 :color ,aluminium4 :style sunken-button)))))
    `(custom-button-mouse ((,class (:background ,aluminium4 :foreground ,aluminium0 :box (:line-width 2 :color ,aluminium4 :style sunken-button)))))
    `(custom-button-pressed ((,class (:background ,aluminium6 :foreground ,aluminium0 :box (:line-width 2 :color ,aluminium4 :style sunken-button)))))
    `(custom-button-pressed-unraised ((,class (:background ,aluminium4 :foreground ,aluminium0 :box (:line-width 2 :color ,aluminium4 :style sunken-button)))))
    `(custom-button-unraised ((,class (:background ,aluminium0 :foreground ,aluminium8 :box (:line-width 2 :color ,aluminium4 :style sunken-button)))))
    `(custom-changed ((,class (:foreground ,aluminium13))))
    `(custom-comment ((,class (:foreground ,aluminium-comment))))
    `(custom-comment-tag ((,class (:foreground ,aluminium7))))
    `(custom-documentation ((,class (:foreground ,aluminium4))))
    `(custom-group-tag ((,class (:foreground ,aluminium8 :weight bold))))
    `(custom-group-tag-1 ((,class (:foreground ,aluminium8 :weight bold))))
    `(custom-invalid ((,class (:foreground ,aluminium11))))
    `(custom-modified ((,class (:foreground ,aluminium13))))
    `(custom-rogue ((,class (:foreground ,aluminium12 :background ,aluminium2))))
    `(custom-saved ((,class (:foreground ,aluminium14))))
    `(custom-set ((,class (:foreground ,aluminium8))))
    `(custom-state ((,class (:foreground ,aluminium14))))
    `(custom-themed ((,class (:foreground ,aluminium8 :background ,aluminium2))))
    `(cursor ((,class (:background ,aluminium4))))
    `(fringe ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(file-name-shadow ((,class (:inherit shadow))))
    `(header-line ((,class (:foreground ,aluminium4 :background ,aluminium2))))
    `(help-argument-name ((,class (:foreground ,aluminium8))))
    `(highlight ((,class (:foreground ,aluminium8 :background ,aluminium2))))
    `(hl-line ((,class (:background ,aluminium1))))
    `(info-menu-star ((,class (:foreground ,aluminium9))))
    `(isearch ((,class (:foreground ,aluminium0 :background ,aluminium8))))
    `(isearch-fail ((,class (:foreground ,aluminium11))))
    `(link ((,class (:underline t))))
    `(link-visited ((,class (:underline t))))
    `(linum ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(linum-relative-current-face ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(match ((,class (:inherit isearch))))
    `(message-cited-text ((,class (:foreground ,aluminium4))))
    `(message-header-cc ((,class (:foreground ,aluminium9))))
    `(message-header-name ((,class (:foreground ,aluminium7))))
    `(message-header-newsgroup ((,class (:foreground ,aluminium14))))
    `(message-header-other ((,class (:foreground ,aluminium4))))
    `(message-header-subject ((,class (:foreground ,aluminium8))))
    `(message-header-to ((,class (:foreground ,aluminium9))))
    `(message-header-xheader ((,class (:foreground ,aluminium13))))
    `(message-mml ((,class (:foreground ,aluminium10))))
    `(message-separator ((,class (:inherit shadow))))
    `(minibuffer-prompt ((,class (:foreground ,aluminium8 :weight bold))))
    `(mm-command-output ((,class (:foreground ,aluminium8))))
    `(mode-line ((,class (:foreground ,aluminium-comment :background ,aluminium0 :overline ,aluminium2))))
    `(mode-line-buffer-id ((,class (:weight bold))))
    `(mode-line-highlight ((,class (:foreground ,aluminium-comment :background ,aluminium0 :overline ,aluminium2))))
    `(mode-line-inactive ((,class (:foreground ,aluminium-comment :background ,aluminium-uniform-mode-lines-background :overline ,aluminium2))))
    `(next-error ((,class (:inherit error))))
    `(nobreak-space ((,class (:foreground ,aluminium3))))
    `(outline-1 ((,class (:foreground ,aluminium8 :weight bold))))
    `(outline-2 ((,class (:inherit outline-1))))
    `(outline-3 ((,class (:inherit outline-1))))
    `(outline-4 ((,class (:inherit outline-1))))
    `(outline-5 ((,class (:inherit outline-1))))
    `(outline-6 ((,class (:inherit outline-1))))
    `(outline-7 ((,class (:inherit outline-1))))
    `(outline-8 ((,class (:inherit outline-1))))
    `(package-description ((,class (:foreground ,aluminium4))))
    `(package-help-section-name ((,class (:foreground ,aluminium8 :weight bold))))
    `(package-name ((,class (:foreground ,aluminium8))))
    `(package-status-available ((,class (:foreground ,aluminium7))))
    `(package-status-avail-obso ((,class (:foreground ,aluminium7 :slant italic))))
    `(package-status-built-in ((,class (:foreground ,aluminium9))))
    `(package-status-dependency ((,class (:foreground ,aluminium8 :slant italic))))
    `(package-status-disabled ((,class (:foreground ,aluminium3))))
    `(package-status-external ((,class (:foreground ,aluminium12 :slant italic))))
    `(package-status-held ((,class (:foreground ,aluminium4 :weight bold))))
    `(package-status-new ((,class (:foreground ,aluminium14))))
    `(package-status-incompat ((,class (:foreground ,aluminium11))))
    `(package-status-installed ((,class (:foreground ,aluminium7 :weight bold))))
    `(package-status-unsigned ((,class (:underline ,aluminium13))))
    `(query-replace ((,class (:foreground ,aluminium8 :background ,aluminium2))))
    `(region ((,class (:foreground ,aluminium-region-highlight-foreground :background ,aluminium-region-highlight-background))))
    `(scroll-bar ((,class (:background ,aluminium3))))
    `(secondary-selection ((,class (:background ,aluminium2))))
    `(show-paren-match-face ((,class (:foreground ,aluminium0 :background ,aluminium8))))
    `(show-paren-mismatch-face ((,class (:background ,aluminium11))))
    `(success ((,class (:foreground ,aluminium14))))
    `(term ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(term-color-black ((,class (:foreground ,aluminium5 :background ,aluminium5))))
    `(term-color-white ((,class (:foreground ,aluminium1 :background ,aluminium1))))
    `(term-color-cyan ((,class (:foreground ,aluminium11 :background ,aluminium11))))
    `(term-color-blue ((,class (:foreground ,aluminium13 :background ,aluminium13))))
    `(term-color-red ((,class (:foreground ,aluminium8 :background ,aluminium8))))
    `(term-color-yellow ((,class (:foreground ,aluminium10 :background ,aluminium10))))
    `(term-color-green ((,class (:foreground ,aluminium15 :background ,aluminium15))))
    `(term-color-magenta ((,class (:foreground ,aluminium14 :background ,aluminium14))))
    `(tool-bar ((,class (:foreground ,aluminium4 :background ,aluminium3))))
    `(tooltip ((,class (:foreground ,aluminium0 :background ,aluminium4))))
    `(trailing-whitespace ((,class (:foreground ,aluminium3))))
    `(tty-menu-disabled-face ((,class (:foreground ,aluminium1))))
    `(tty-menu-enabled-face ((,class (:background ,aluminium2 foreground ,aluminium4))))
    `(tty-menu-selected-face ((,class (:foreground ,aluminium8 :underline t))))
    `(undo-tree-visualizer-current-face ((,class (:foreground ,aluminium8))))
    `(undo-tree-visualizer-default-face ((,class (:foreground ,aluminium4))))
    `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,aluminium4))))
    `(undo-tree-visualizer-register-face ((,class (:foreground ,aluminium9))))
    `(vc-conflict-state ((,class (:foreground ,aluminium12))))
    `(vc-edited-state ((,class (:foreground ,aluminium13))))
    `(vc-locally-added-state ((,class (:underline ,aluminium14))))
    `(vc-locked-state ((,class (:foreground ,aluminium10))))
    `(vc-missing-state ((,class (:foreground ,aluminium11))))
    `(vc-needs-update-state ((,class (:foreground ,aluminium12))))
    `(vc-removed-state ((,class (:foreground ,aluminium11))))
    `(vc-state-base ((,class (:foreground ,aluminium4))))
    `(vc-up-to-date-state ((,class (:foreground ,aluminium8))))
    `(vertical-border ((,class (:foreground ,aluminium2))))
    `(which-func ((,class (:foreground ,aluminium8))))
    `(whitespace-big-indent ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-empty ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-hspace ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-indentation ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-line ((,class (:background ,aluminium0))))
    `(whitespace-newline ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-space ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-space-after-tab ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-space-before-tab ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-tab ((,class (:foreground ,aluminium3 :background ,aluminium0))))
    `(whitespace-trailing ((,class (:inherit trailing-whitespace))))
    `(widget-button-pressed ((,class (:foreground ,aluminium9 :background ,aluminium1))))
    `(widget-documentation ((,class (:foreground ,aluminium4))))
    `(widget-field ((,class (:background ,aluminium2 :foreground ,aluminium4))))
    `(widget-single-line-field ((,class (:background ,aluminium2 :foreground ,aluminium4))))
    `(window-divider ((,class (:background ,aluminium3))))
    `(window-divider-first-pixel ((,class (:background ,aluminium3))))
    `(window-divider-last-pixel ((,class (:background ,aluminium3))))

    ;;;; +-----------------+
    ;;;; + Package Support +
    ;;;; +-----------------+
    ;; +--- Syntax ---+
    ;; > Auctex
    `(font-latex-bold-face ((,class (:inherit bold))))
    `(font-latex-italic-face ((,class (:inherit italic))))
    `(font-latex-math-face ((,class (:foreground ,aluminium8))))
    `(font-latex-sectioning-0-face ((,class (:foreground ,aluminium8 :weight bold))))
    `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))))
    `(font-latex-string-face ((,class (:inherit font-lock-string-face))))
    `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))))

    ;; > Elixir
    `(elixir-attribute-face ((,class (:foreground ,aluminium-annotation))))
    `(elixir-atom-face ((,class (:foreground ,aluminium4 :weight bold))))

    ;; > Enhanced Ruby
    `(enh-ruby-heredoc-delimiter-face ((,class (:foreground ,aluminium14))))
    `(enh-ruby-op-face ((,class (:foreground ,aluminium9))))
    `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,aluminium13))))
    `(enh-ruby-regexp-face ((,class (:foreground ,aluminium13))))
    `(enh-ruby-string-delimiter-face ((,class (:foreground ,aluminium14))))
    `(erm-syn-errline ((,class (:foreground ,aluminium11 :underline t))))
    `(erm-syn-warnline ((,class (:foreground ,aluminium13 :underline t))))

    ;; > Java Development Environment for Emacs
    `(jdee-db-active-breakpoint-face ((,class (:background ,aluminium2 :weight bold))))
    `(jdee-bug-breakpoint-cursor ((,class (:background ,aluminium2))))
    `(jdee-db-requested-breakpoint-face ((,class (:foreground ,aluminium13 :background ,aluminium2 :weight bold))))
    `(jdee-db-spec-breakpoint-face ((,class (:foreground ,aluminium14 :background ,aluminium2 :weight bold))))
    `(jdee-font-lock-api-face ((,class (:foreground ,aluminium4))))
    `(jdee-font-lock-code-face ((,class (:slant italic))))
    `(jdee-font-lock-constant-face ((,class (:foreground ,aluminium-keyword))))
    `(jdee-font-lock-constructor-face ((,class (:foreground ,aluminium-method))))
    `(jdee-font-lock-doc-tag-face ((,class (:foreground ,aluminium7))))
    `(jdee-font-lock-link-face ((,class (:underline t))))
    `(jdee-font-lock-modifier-face ((,class (:foreground ,aluminium-keyword))))
    `(jdee-font-lock-number-face ((,class (:foreground ,aluminium-numeric))))
    `(jdee-font-lock-operator-fac ((,class (:foreground ,aluminium-operator))))
    `(jdee-font-lock-package-face ((,class (:foreground ,aluminium-class))))
    `(jdee-font-lock-pre-face ((,class (:foreground ,aluminium-comment :slant italic))))
    `(jdee-font-lock-private-face ((,class (:foreground ,aluminium-keyword))))
    `(jdee-font-lock-public-face ((,class (:foreground ,aluminium-keyword))))
    `(jdee-font-lock-variable-face ((,class (:foreground ,aluminium-variable))))

    ;; > JavaScript 2
    `(js2-function-call ((,class (:foreground ,aluminium8))))
    `(js2-private-function-call ((,class (:foreground ,aluminium8))))
    `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,aluminium6))))
    `(js2-jsdoc-html-tag-name ((,class (:foreground ,aluminium9))))
    `(js2-external-variable ((,class (:foreground ,aluminium4))))
    `(js2-function-param ((,class (:foreground ,aluminium4))))
    `(js2-jsdoc-value ((,class (:foreground ,aluminium-comment))))
    `(js2-jsdoc-tag ((,class (:foreground ,aluminium7))))
    `(js2-jsdoc-type ((,class (:foreground ,aluminium7))))
    `(js2-private-member ((,class (:foreground ,aluminium4))))
    `(js2-object-property ((,class (:foreground ,aluminium4))))
    `(js2-error ((,class (:foreground ,aluminium11))))
    `(js2-warning ((,class (:foreground ,aluminium13))))
    `(js2-instance-member ((,class (:foreground ,aluminium4))))

    ;; > JavaScript 3
    `(js3-error-face ((,class (:foreground ,aluminium11))))
    `(js3-external-variable-face ((,class (:foreground ,aluminium4))))
    `(js3-function-param-face ((,class (:foreground ,aluminium4))))
    `(js3-instance-member-face ((,class (:foreground ,aluminium4))))
    `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,aluminium6))))
    `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,aluminium9))))
    `(js3-jsdoc-tag-face ((,class (:foreground ,aluminium9))))
    `(js3-jsdoc-type-face ((,class (:foreground ,aluminium7))))
    `(js3-jsdoc-value-face ((,class (:foreground ,aluminium4))))
    `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
    `(js3-private-function-call-face ((,class (:foreground ,aluminium8))))
    `(js3-private-member-face ((,class (:foreground ,aluminium4))))
    `(js3-warning-face ((,class (:foreground ,aluminium13))))

    ;; > Markdown
    `(markdown-blockquote-face ((,class (:foreground ,aluminium-comment))))
    `(markdown-bold-face ((,class (:inherit bold))))
    `(markdown-header-face-1 ((,class (:foreground ,aluminium8))))
    `(markdown-header-face-2 ((,class (:foreground ,aluminium8))))
    `(markdown-header-face-3 ((,class (:foreground ,aluminium8))))
    `(markdown-header-face-4 ((,class (:foreground ,aluminium8))))
    `(markdown-header-face-5 ((,class (:foreground ,aluminium8))))
    `(markdown-header-face-6 ((,class (:foreground ,aluminium8))))
    `(markdown-inline-code-face ((,class (:foreground ,aluminium7))))
    `(markdown-italic-face ((,class (:inherit italic))))
    `(markdown-link-face ((,class (:foreground ,aluminium8))))
    `(markdown-markup-face ((,class (:foreground ,aluminium9))))
    `(markdown-reference-face ((,class (:inherit markdown-link-face))))
    `(markdown-url-face ((,class (:foreground ,aluminium4 :underline t))))

    ;; > Rainbow Delimeters
    `(rainbow-delimiters-depth-1-face ((,class :foreground ,aluminium7)))
    `(rainbow-delimiters-depth-2-face ((,class :foreground ,aluminium8)))
    `(rainbow-delimiters-depth-3-face ((,class :foreground ,aluminium9)))
    `(rainbow-delimiters-depth-4-face ((,class :foreground ,aluminium10)))
    `(rainbow-delimiters-depth-5-face ((,class :foreground ,aluminium12)))
    `(rainbow-delimiters-depth-6-face ((,class :foreground ,aluminium13)))
    `(rainbow-delimiters-depth-7-face ((,class :foreground ,aluminium14)))
    `(rainbow-delimiters-depth-8-face ((,class :foreground ,aluminium15)))
    `(rainbow-delimiters-unmatched-face ((,class :foreground ,aluminium11)))

    ;; > Web Mode
    `(web-mode-attr-tag-custom-face ((,class (:foreground ,aluminium-attribute))))
    `(web-mode-builtin-face ((,class (:foreground ,aluminium-keyword))))
    `(web-mode-comment-face ((,class (:foreground ,aluminium-comment))))
    `(web-mode-comment-keyword-face ((,class (:foreground ,aluminium-comment))))
    `(web-mode-constant-face ((,class (:foreground ,aluminium-variable))))
    `(web-mode-css-at-rule-face ((,class (:foreground ,aluminium-annotation))))
    `(web-mode-css-function-face ((,class (:foreground ,aluminium-method))))
    `(web-mode-css-property-name-face ((,class (:foreground ,aluminium-keyword))))
    `(web-mode-css-pseudo-class-face ((,class (:foreground ,aluminium-class))))
    `(web-mode-css-selector-face ((,class (:foreground ,aluminium-keyword))))
    `(web-mode-css-string-face ((,class (:foreground ,aluminium-string))))
    `(web-mode-doctype-face ((,class (:foreground ,aluminium-preprocessor))))
    `(web-mode-function-call-face ((,class (:foreground ,aluminium-method))))
    `(web-mode-function-name-face ((,class (:foreground ,aluminium-method))))
    `(web-mode-html-attr-name-face ((,class (:foreground ,aluminium-attribute))))
    `(web-mode-html-attr-equal-face ((,class (:foreground ,aluminium-punctuation))))
    `(web-mode-html-attr-value-face ((,class (:foreground ,aluminium-string))))
    `(web-mode-html-entity-face ((,class (:foreground ,aluminium-keyword))))
    `(web-mode-html-tag-bracket-face ((,class (:foreground ,aluminium-punctuation))))
    `(web-mode-html-tag-custom-face ((,class (:foreground ,aluminium-tag))))
    `(web-mode-html-tag-face ((,class (:foreground ,aluminium-tag))))
    `(web-mode-html-tag-namespaced-face ((,class (:foreground ,aluminium-keyword))))
    `(web-mode-json-key-face ((,class (:foreground ,aluminium-class))))
    `(web-mode-json-string-face ((,class (:foreground ,aluminium-string))))
    `(web-mode-keyword-face ((,class (:foreground ,aluminium-keyword))))
    `(web-mode-preprocessor-face ((,class (:foreground ,aluminium-preprocessor))))
    `(web-mode-string-face ((,class (:foreground ,aluminium-string))))
    `(web-mode-symbol-face ((,class (:foreground ,aluminium-variable))))
    `(web-mode-type-face ((,class (:foreground ,aluminium-class))))
    `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
    `(web-mode-variable-name-face ((,class (:foreground ,aluminium-variable))))

    ;; +--- UI ---+
    ;; > Anzu
    `(anzu-mode-line ((,class (:foreground, aluminium8))))
    `(anzu-mode-line-no-match ((,class (:foreground, aluminium11))))

    ;; > Avy
    `(avy-lead-face ((,class (:background ,aluminium11 :foreground ,aluminium5))))
    `(avy-lead-face-0 ((,class (:background ,aluminium10 :foreground ,aluminium5))))
    `(avy-lead-face-1 ((,class (:background ,aluminium3 :foreground ,aluminium5))))
    `(avy-lead-face-2 ((,class (:background ,aluminium15 :foreground ,aluminium5))))

    ;; > Company
    `(company-echo-common ((,class (:foreground ,aluminium0 :background ,aluminium4))))
    `(company-preview ((,class (:foreground ,aluminium4 :background ,aluminium10))))
    `(company-preview-common ((,class (:foreground ,aluminium0 :background ,aluminium8))))
    `(company-preview-search ((,class (:foreground ,aluminium0 :background ,aluminium8))))
    `(company-scrollbar-bg ((,class (:foreground ,aluminium1 :background ,aluminium1))))
    `(company-scrollbar-fg ((,class (:foreground ,aluminium2 :background ,aluminium2))))
    `(company-template-field ((,class (:foreground ,aluminium0 :background ,aluminium7))))
    `(company-tooltip ((,class (:foreground ,aluminium4 :background ,aluminium2))))
    `(company-tooltip-annotation ((,class (:foreground ,aluminium12))))
    `(company-tooltip-annotation-selection ((,class (:foreground ,aluminium12 :weight bold))))
    `(company-tooltip-common ((,class (:foreground ,aluminium8))))
    `(company-tooltip-common-selection ((,class (:foreground ,aluminium8 :background ,aluminium3))))
    `(company-tooltip-mouse ((,class (:inherit highlight))))
    `(company-tooltip-selection ((,class (:background ,aluminium3 :weight bold))))

    ;; > diff-hl
   `(diff-hl-change ((,class (:background ,aluminium13))))
   `(diff-hl-insert ((,class (:background ,aluminium14))))
   `(diff-hl-delete ((,class (:background ,aluminium11))))

    ;; > Evil
    `(evil-ex-info ((,class (:foreground ,aluminium8))))
    `(evil-ex-substitute-replacement ((,class (:foreground ,aluminium9))))
    `(evil-ex-substitute-matches ((,class (:inherit isearch))))

    ;; > Flycheck
    `(flycheck-error ((,class (:underline (:style wave :color ,aluminium11)))))
    `(flycheck-fringe-error ((,class (:foreground ,aluminium11 :weight bold))))
    `(flycheck-fringe-info ((,class (:foreground ,aluminium8 :weight bold))))
    `(flycheck-fringe-warning ((,class (:foreground ,aluminium13 :weight bold))))
    `(flycheck-info ((,class (:underline (:style wave :color ,aluminium8)))))
    `(flycheck-warning ((,class (:underline (:style wave :color ,aluminium13)))))

    ;; > Git Gutter
    `(git-gutter:modified ((,class (:foreground ,aluminium13))))
    `(git-gutter:added ((,class (:foreground ,aluminium14))))
    `(git-gutter:deleted ((,class (:foreground ,aluminium11))))

    ;; > Git Gutter Plus
    `(git-gutter+-modified ((,class (:foreground ,aluminium13))))
    `(git-gutter+-added ((,class (:foreground ,aluminium14))))
    `(git-gutter+-deleted ((,class (:foreground ,aluminium11))))

    ;; > Helm
    `(helm-bookmark-addressbook ((,class (:foreground ,aluminium7))))
    `(helm-bookmark-directory ((,class (:foreground ,aluminium9))))
    `(helm-bookmark-file ((,class (:foreground ,aluminium8))))
    `(helm-bookmark-gnus ((,class (:foreground ,aluminium10))))
    `(helm-bookmark-info ((,class (:foreground ,aluminium14))))
    `(helm-bookmark-man ((,class (:foreground ,aluminium4))))
    `(helm-bookmark-w3m ((,class (:foreground ,aluminium9))))
    `(helm-buffer-directory ((,class (:foreground ,aluminium9))))
    `(helm-buffer-file ((,class (:foreground ,aluminium8))))
    `(helm-buffer-not-saved ((,class (:foreground ,aluminium13))))
    `(helm-buffer-process ((,class (:foreground ,aluminium10))))
    `(helm-candidate-number ((,class (:foreground ,aluminium4 :weight bold))))
    `(helm-candidate-number-suspended ((,class (:foreground ,aluminium4))))
    `(helm-ff-directory ((,class (:foreground ,aluminium9 :weight bold))))
    `(helm-ff-dirs ((,class (:foreground ,aluminium9))))
    `(helm-ff-dotted-director ((,class (:foreground ,aluminium9 :underline t))))
    `(helm-ff-dotted-symlink-director ((,class (:foreground ,aluminium7 :weight bold))))
    `(helm-ff-executable ((,class (:foreground ,aluminium8))))
    `(helm-ff-file ((,class (:foreground ,aluminium4))))
    `(helm-ff-invalid-symlink ((,class (:foreground ,aluminium11 :weight bold))))
    `(helm-ff-prefix ((,class (:foreground ,aluminium0 :background ,aluminium9))))
    `(helm-ff-symlink ((,class (:foreground ,aluminium7))))
    `(helm-grep-cmd-line ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(helm-grep-file ((,class (:foreground ,aluminium8))))
    `(helm-grep-finish ((,class (:foreground ,aluminium5))))
    `(helm-grep-lineno ((,class (:foreground ,aluminium4))))
    `(helm-grep-match ((,class (:inherit isearch))))
    `(helm-grep-running ((,class (:foreground ,aluminium8))))
    `(helm-header ((,class (:foreground ,aluminium9 :background ,aluminium2))))
    `(helm-header-line-left-margin ((,class (:foreground ,aluminium9 :background ,aluminium2))))
    `(helm-history-deleted ((,class (:foreground ,aluminium11))))
    `(helm-history-remote ((,class (:foreground ,aluminium4))))
    `(helm-lisp-completion-info ((,class (:foreground ,aluminium4 :weight bold))))
    `(helm-lisp-show-completion ((,class (:inherit isearch))))
    `(helm-locate-finish ((,class (:foreground ,aluminium14))))
    `(helm-match ((,class (:foreground ,aluminium8))))
    `(helm-match-item ((,class (:inherit isearch))))
    `(helm-moccur-buffer ((,class (:foreground ,aluminium8))))
    `(helm-resume-need-update ((,class (:foreground ,aluminium0 :background ,aluminium13))))
    `(helm-selection ((,class (:inherit highlight))))
    `(helm-selection-line ((,class (:background ,aluminium2))))
    `(helm-source-header ((,class (:height 1.44 :foreground ,aluminium8 :background ,aluminium2))))
    `(helm-swoop-line-number-face ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(helm-swoop-target-word-face ((,class (:foreground ,aluminium0 :background ,aluminium7))))
    `(helm-swoop-target-line-face ((,class (:background ,aluminium13 :foreground ,aluminium3))))
    `(helm-swoop-target-line-block-face ((,class (:background ,aluminium13 :foreground ,aluminium3))))
    `(helm-separator ((,class (:background ,aluminium2))))
    `(helm-visible-mark ((,class (:background ,aluminium2))))

    ;; > Magit
    `(magit-branch ((,class (:foreground ,aluminium7 :weight bold))))
    `(magit-diff-context-highlight ((,class (:background ,aluminium2))))
    `(magit-diff-file-header ((,class (:foreground ,aluminium8 :box (:color ,aluminium8)))))
    `(magit-diffstat-added ((,class (:foreground ,aluminium14))))
    `(magit-diffstat-removed ((,class (:foreground ,aluminium11))))
    `(magit-hash ((,class (:foreground ,aluminium8))))
    `(magit-hunk-heading ((,class (:foreground ,aluminium9))))
    `(magit-hunk-heading-highlight ((,class (:foreground ,aluminium9 :background ,aluminium2))))
    `(magit-item-highlight ((,class (:foreground ,aluminium8 :background ,aluminium2))))
    `(magit-log-author ((,class (:foreground ,aluminium7))))
    `(magit-process-ng ((,class (:foreground ,aluminium13 :weight bold))))
    `(magit-process-ok ((,class (:foreground ,aluminium14 :weight bold))))
    `(magit-section-heading ((,class (:foreground ,aluminium7 :weight bold))))
    `(magit-section-highlight ((,class (:background ,aluminium2))))

    ;; > MU4E
    `(mu4e-header-marks-face ((,class (:foreground ,aluminium9))))
    `(mu4e-title-face ((,class (:foreground ,aluminium8))))
    `(mu4e-header-key-face ((,class (:foreground ,aluminium8))))
    `(mu4e-highlight-face ((,class (:highlight))))
    `(mu4e-flagged-face ((,class (:foreground ,aluminium13))))
    `(mu4e-unread-face ((,class (:foreground ,aluminium13 :weight bold))))
    `(mu4e-link-face ((,class (:underline t))))

    ;; > Powerline
    `(powerline-active1 ((,class (:foreground ,aluminium-comment :background ,aluminium0))))
    `(powerline-active2 ((,class (:foreground ,aluminium-comment :background ,aluminium0))))
    `(powerline-inactive1 ((,class (:background ,aluminium0))))
    `(powerline-inactive2 ((,class (:background ,aluminium0))))

    ;; > Powerline Evil
    `(powerline-evil-base-face ((,class (:foreground ,aluminium4))))
    `(powerline-evil-normal-face ((,class (:background ,aluminium8))))
    `(powerline-evil-insert-face ((,class (:foreground ,aluminium0 :background ,aluminium4))))
    `(powerline-evil-visual-face ((,class (:foreground ,aluminium0 :background ,aluminium7))))
    `(powerline-evil-replace-face ((,class (:foreground ,aluminium0 :background ,aluminium9))))

    `(spaceline-evil-normal    ((,class (:foreground ,aluminium8 :background ,aluminium0))))
    `(spacemacs-replace-face   ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(spaceline-evil-replace   ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(spacemacs-insert-face    ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(spaceline-evil-insert    ((,class (:foreground ,aluminium4 :background ,aluminium0))))
    `(spacemacs-motion-face    ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(spaceline-evil-motion    ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(spacemacs-visual-face    ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(spaceline-evil-visual    ((,class (:foreground ,aluminium9 :background ,aluminium0))))
    `(spaceline-highlight-face ((,class (:foreground ,aluminium8 :background ,aluminium0))))

    ;; > NeoTree
    `(neo-banner-face ((,class (:foreground ,aluminium10))))
    `(neo-dir-link-face ((,class (:foreground ,aluminium9))))
    `(neo-expand-btn-face ((,class (:foreground ,aluminium6 :bold t))))
    `(neo-file-link-face ((,class (:foreground ,aluminium4))))
    `(neo-root-dir-face ((,class (:foreground ,aluminium7 :weight bold))))
    `(neo-vc-added-face ((,class (:foreground ,aluminium14))))
    `(neo-vc-conflict-face ((,class (:foreground ,aluminium11))))
    `(neo-vc-default-face ((,class (:foreground ,aluminium4))))
    `(neo-vc-edited-face ((,class (:foreground ,aluminium13))))
    `(neo-vc-ignored-face ((,class (:foreground ,aluminium3))))
    `(neo-vc-missing-face ((,class (:foreground ,aluminium12))))
    `(neo-vc-needs-merge-face ((,class (:background ,aluminium12 :foreground ,aluminium4))))
    `(neo-vc-needs-update-face ((,class (:background ,aluminium10 :foreground ,aluminium4))))
    `(neo-vc-removed-face ((,class (:foreground ,aluminium11 :strike-through nil))))
    `(neo-vc-up-to-date-face ((,class (:foreground ,aluminium4))))
    `(neo-vc-user-face ((,class (:foreground ,aluminium4))))

    ;; > Org
    `(org-level-1 ((,class (:foreground ,aluminium8 :weight bold))))
    `(org-level-2 ((,class (:inherit org-level-1))))
    `(org-level-3 ((,class (:inherit org-level-1))))
    `(org-level-4 ((,class (:inherit org-level-1))))
    `(org-level-5 ((,class (:inherit org-level-1))))
    `(org-level-6 ((,class (:inherit org-level-1))))
    `(org-level-7 ((,class (:inherit org-level-1))))
    `(org-level-8 ((,class (:inherit org-level-1))))
    `(org-agenda-structure ((,class (:foreground ,aluminium9))))
    `(org-agenda-date ((,class (:foreground ,aluminium8 :underline nil))))
    `(org-agenda-done ((,class (:foreground ,aluminium14))))
    `(org-agenda-dimmed-todo-face ((,class (:background ,aluminium13))))
    `(org-block ((,class (:foreground ,aluminium4))))
    `(org-block-background ((,class (:background ,aluminium0))))
    `(org-block-begin-line ((,class (:foreground ,aluminium7))))
    `(org-block-end-line ((,class (:foreground ,aluminium7))))
    `(org-checkbox ((,class (:foreground ,aluminium9))))
    `(org-checkbox-statistics-done ((,class (:foreground ,aluminium14))))
    `(org-checkbox-statistics-todo ((,class (:foreground ,aluminium13))))
    `(org-code ((,class (:foreground ,aluminium7))))
    `(org-column ((,class (:background ,aluminium2))))
    `(org-column-title ((,class (:inherit org-column :weight bold :underline t))))
    `(org-date ((,class (:foreground ,aluminium8))))
    `(org-document-info ((,class (:foreground ,aluminium4))))
    `(org-document-info-keyword ((,class (:foreground ,aluminium3 :weight bold))))
    `(org-document-title ((,class (:foreground ,aluminium8 :weight bold))))
    `(org-done ((,class (:foreground ,aluminium14 :weight bold))))
    `(org-ellipsis ((,class (:foreground ,aluminium3))))
    `(org-footnote ((,class (:foreground ,aluminium8))))
    `(org-formula ((,class (:foreground ,aluminium9))))
    `(org-hide ((,class (:foreground ,aluminium0 :background ,aluminium0))))
    `(org-link ((,class (:underline t))))
    `(org-scheduled ((,class (:foreground ,aluminium14))))
    `(org-scheduled-previously ((,class (:foreground ,aluminium13))))
    `(org-scheduled-today ((,class (:foreground ,aluminium8))))
    `(org-special-keyword ((,class (:foreground ,aluminium9))))
    `(org-table ((,class (:foreground ,aluminium9))))
    `(org-todo ((,class (:foreground ,aluminium13 :weight bold))))
    `(org-upcoming-deadline ((,class (:foreground ,aluminium12))))
    `(org-warning ((,class (:foreground ,aluminium13 :weight bold))))
    `(font-latex-bold-face ((,class (:inherit bold))))
    `(font-latex-italic-face ((,class (:slant italic))))
    `(font-latex-string-face ((,class (:foreground ,aluminium14))))
    `(font-latex-match-reference-keywords ((,class (:foreground ,aluminium9))))
    `(font-latex-match-variable-keywords ((,class (:foreground ,aluminium4))))
    `(ido-only-match ((,class (:foreground ,aluminium8))))
    `(org-sexp-date ((,class (:foreground ,aluminium7))))
    `(ido-first-match ((,class (:foreground ,aluminium8 :weight bold))))
    `(ido-subdir ((,class (:foreground ,aluminium9))))
    `(org-quote ((,class (:inherit org-block :slant italic))))
    `(org-verse ((,class (:inherit org-block :slant italic))))
    `(org-agenda-date-weekend ((,class (:foreground ,aluminium9))))
    `(org-agenda-date-today ((,class (:foreground ,aluminium8 :weight bold))))
    `(org-agenda-done ((,class (:foreground ,aluminium14))))
    `(org-verbatim ((,class (:foreground ,aluminium7))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
    (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'aluminium)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

;;; aluminium-theme.el ends here
